### ISSUE TITLE
你好，请问多个域名怎么设置

### ISSUE THREAD

**Issue by wzh154710510** [pboymt/ddns-at-home#1]
Resourcerecord 是否支持多个域名

**Comment by pboymt** [comment]
暂时还不支持，不过实现还是很容易的😅



---原始邮件---
发件人: "wzh154710510"<notifications@github.com&gt;
发送时间: 2020年1月21日(周二) 下午4:23
收件人: "pboymt/aliyun-ddns"<aliyun-ddns@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [pboymt/aliyun-ddns] 你好，请问多个域名怎么设置 (#1)



Resourcerecord 是否支持多个域名

**Comment by wzh154710510** [comment]
求更新

**Comment by pboymt** [comment]
已经更新啦！欢迎帮我推广这个工具哦。
